#!/bin/bash

#PLATFORM_VERSION_CODENAME=AOSP
#PLATFORM_VERSION=4.0.3.0.2.0.1.0
#TARGET_PRODUCT=full
#TARGET_BUILD_VARIANT=eng
#TARGET_BUILD_TYPE=release
#TARGET_BUILD_APPS=
#TARGET_ARCH=arm
#TARGET_ARCH_VARIANT=armv7-a
#HOST_ARCH=x86
#HOST_OS=linux
#HOST_BUILD_TYPE=release
#BUILD_ID=OPENMASTER
#OUT_DIR=out

# NDK_LOG=1 
# NDK_ANALYZE=1
# APP_BUILD_SCRIPT=Android.mk 
# APP_PLATFORM=android-8
# LOCAL_MODULE=bionic



CURDIR=`pwd`

/home/appos/DevSoft/android-ndk-r8d/ndk-build \
	NDK_LOG=1 \
	NDK_PROJECT_PATH=$CURDIR \
	APP_BUILD_SCRIPT=$CURDIR/Android.mk

